services:
  localdb:
    user: 499:499
    build: localdb
    container_name: localdb
    volumes:
      - ./localdb:/localdb
    environment:
      - MONGO_DB_NAME=prod_db
      - MONGO_URI=mongodb://${MONGODB_INITDB_ROOT_USERNAME}:${MONGODB_INITDB_ROOT_PASSWORD}@mongodb:27017
      - TESTING=False

    sysctls:
            -  "net.ipv4.ping_group_range=0 100000"
    restart: always
    ports:
    - "5000:5000"

  caen:
    user: 499:499
    build: caen
    container_name: caen
    sysctls:
            -  "net.ipv4.ping_group_range=0 100000"
    volumes:
      - ./caenconfig.xml:/config.xml
      - ./caen/caen_server.sh:/caen_server.sh
      - /scratch/CAENHVWrapper-6.3.tgz:/CAENHVWrapper-6.3.tgz
    restart: always
    ports:
    - "7000:7000" 
  testnode:
    build: testnode 
    volumes:
      - type: bind
        source: ${DATA_PREFIX}/scratch/opt/testnode
        target: /opt
  ble-mqtt:
    user: 0:0
    container_name: ble-mqtt
    build: ble-mqtt
    privileged: true
    tty: true
    stdin_open: true
    restart: always
    network_mode: host
    volumes:
      - /var/run/dbus/:/var/run/dbus/:z
      - ./ble-mqtt/:/scripts/
    #depends_on: 
    #  - mosquitto
  coldroom-mqtt:
    container_name: coldroom-mqtt
    user: 499:499
    build: coldroom-mqtt
    restart: always
    environment:
      - COLDROOM_USERNAME=${COLDROOM_USERNAME}
      - COLDROOM_PASSWORD=${COLDROOM_PASSWORD}
    depends_on: 
      - mosquitto
  caen-mqtt:
    container_name: caen-mqtt
    user: 499:499
    build: caen-mqtt
    restart: always
    depends_on: 
      - caen
      - mosquitto
  mosquitto:
    image: eclipse-mosquitto
    user: 499:499
    volumes:
    - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    - ${DATA_PREFIX}/mosquitto/log:/mosquitto/log
    - ${DATA_PREFIX}/mosquitto/data/:/mosquitto/data
    restart: always
    ports:
    - "1883:1883" 
    container_name: mosquitto
  influxdb:
    user: 499:499
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - ${DATA_PREFIX}/influxdb/influxdb-data:/var/lib/influxdb2
      - ${DATA_PREFIX}/influxdb-config/:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${INITMODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXUSER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXPASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=pisaoutertracker
      - DOCKER_INFLUXDB_INIT_BUCKET=sensor_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXTOKEN}
  
  telegraf:
    user: 499:499
    image: telegraf
    container_name: telegraf
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - mosquitto
      - influxdb
  
  grafana:
    user: 499:499
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
      - ${DATA_PREFIX}/grafana/grafana-data:/var/lib/grafana
    depends_on:
      - influxdb


#  mongodbtestapp:
#    image: mongodb/mongodb-community-server:6.0-ubi8
#    environment:
#            - CONN_STR=mongodb://${MONGODB_INITDB_ROOT_USERNAME}:${MONGODB_INITDB_ROOT_PASSWORD}@mongodb
#    command: '/bin/bash -c "sleep 5; mongosh $$CONN_STR --eval \"show dbs;\""'
#    depends_on:
#      - mongodb
  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:6.0-ubi8
    user: 499:499
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_INITDB_ROOT_USERNAME}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_INITDB_ROOT_PASSWORD}
    volumes:
      - type: bind
        source: /scratch/opt/MongoDB/data 
        target: /data/db
    ports:
      - "27017:27017"
